#!/usr/bin/env bash
# Deploys the frontend to S3, injecting the current API URL.
# Run AFTER `terraform apply` (so the API + bucket exist).
set -euo pipefail

ENV_DIR="terraform/environments/dev"
API_URL="$(terraform -chdir="$ENV_DIR" output -raw api_url)"
BUCKET="$(terraform -chdir="$ENV_DIR" output -raw website_bucket)"
WEBSITE="$(terraform -chdir="$ENV_DIR" output -raw website_url)"

# Inject the current API URL into config.js
echo "// Auto-generated by scripts/deploy_ui.sh" > frontend/config.js
echo "window.API_BASE_URL = \"${API_URL}\";" >> frontend/config.js

# Upload each file with an EXPLICIT Content-Type (so the browser applies the
# CSS/JS) and no-cache (so re-uploads show immediately during development).
aws s3 cp frontend/index.html "s3://${BUCKET}/index.html" \
  --content-type "text/html" --cache-control "no-cache"
aws s3 cp frontend/styles.css "s3://${BUCKET}/styles.css" \
  --content-type "text/css" --cache-control "no-cache"
aws s3 cp frontend/app.js "s3://${BUCKET}/app.js" \
  --content-type "application/javascript" --cache-control "no-cache"
aws s3 cp frontend/config.js "s3://${BUCKET}/config.js" \
  --content-type "application/javascript" --cache-control "no-cache"

echo ""
echo "✅ UI deployed!"
echo "   API:     ${API_URL}"
echo "   Website: ${WEBSITE}"
echo "   Tip: hard-refresh the browser (Ctrl+Shift+R) to bypass cache."
